import { CONFIG, EVENT_TYPES } from '../config.js?v=__BUILD_ID__';

const API_BASE = 'https://www.googleapis.com/calendar/v3';

export function classifyEvent(event) {
  const summary = event.summary || '';
  for (const type of EVENT_TYPES) {
    if (type.default) continue;
    if (type.patterns.some((p) => p.test(summary))) {
      return type;
    }
  }

  const colorId = event.colorId != null ? String(event.colorId) : '';
  const mappedTypeId = CONFIG.colorTypeMap?.[colorId];
  if (mappedTypeId) {
    const mapped = EVENT_TYPES.find((t) => t.id === mappedTypeId);
    if (mapped) return mapped;
  }

  return EVENT_TYPES.find((t) => t.default);
}

export function isPrivateEvent(event) {
  const visibility = event.visibility || 'default';
  return visibility === 'private' || visibility === 'confidential';
}

const BOOKING_SESSION_TYPES = [
  {
    id: 'training',
    patterns: [/session with a coach/i, /сесси[яи]\s+с\s+тренер/i, /เซสชันกับโค้ช/i],
  },
  {
    id: '3x3',
    patterns: [/3\s*[x×]\s*3/i],
  },
  {
    id: 'open',
    patterns: [/open play/i, /индивидуальн/i, /เล่นคนเดียว/i],
  },
  {
    id: 'fullcourt',
    patterns: [/full\s*court/i, /весь\s+корт/i, /ทั้งสนาม/i],
  },
];

function extractDescriptionField(description, label) {
  const line = description
    .split('\n')
    .find((value) => new RegExp(`^\\s*${label}\\s*:`, 'i').test(value));
  return line ? line.replace(new RegExp(`^\\s*${label}\\s*:\\s*`, 'i'), '').trim() : '';
}

function parseBookingSessionType(value) {
  if (!value) return null;
  return BOOKING_SESSION_TYPES.find((type) =>
    type.patterns.some((pattern) => pattern.test(value)),
  )?.id || null;
}

/**
 * Parse booking links generated by this site into locale-neutral data.
 * Names remain verbatim; all other values can then be rendered in the viewer's locale.
 */
export function parseBookingDetails(summary, description) {
  const text = String(description || '').replace(/<br\s*\/?>/gi, '\n');
  if (!/(?:^|\n)\s*Island Heats court\s*(?:\n|$)/i.test(text)) return null;

  const playersValue = extractDescriptionField(text, 'Players?');
  const typeValue = extractDescriptionField(text, 'Type');
  const priceValue = extractDescriptionField(text, 'Price');
  const playerMatch = playersValue.match(/6\+|\d+/);
  const priceMatch = priceValue.match(/(\d[\d\s,.]*)(\+)?/);
  const sessionTypeId =
    parseBookingSessionType(typeValue) || parseBookingSessionType(summary);

  return {
    name: extractDescriptionField(text, 'Name'),
    players: playerMatch?.[0] || null,
    sessionTypeId,
    priceAmount: priceMatch
      ? Number(priceMatch[1].replace(/[\s,.]/g, ''))
      : null,
    pricePlus: Boolean(priceMatch?.[2]),
  };
}

/** Extract player count from event description, e.g. "Players: 4 players". */
export function extractPlayersFromDescription(description) {
  if (!description) return null;
  const text = String(description).replace(/<br\s*\/?>/gi, '\n');
  const match =
    text.match(/(?:players?|игроки?|чел\.?|คน)\s*[:=]?\s*(6\+|[\d]+)/i) ||
    text.match(/(?:👥)\s*(6\+|[\d]+)/);
  if (!match) return null;
  return match[1];
}

export function parseEvent(event) {
  const start = event.start?.dateTime || event.start?.date;
  const end = event.end?.dateTime || event.end?.date;
  const allDay = Boolean(event.start?.date && !event.start?.dateTime);
  const isPrivate = isPrivateEvent(event);
  const description = isPrivate ? null : event.description || '';
  const booking = isPrivate
    ? null
    : parseBookingDetails(event.summary || '', description);
  const type =
    EVENT_TYPES.find((candidate) => candidate.id === booking?.sessionTypeId) ||
    classifyEvent(event);

  return {
    id: event.id,
    summary: isPrivate ? null : event.summary || '',
    description,
    players: isPrivate
      ? null
      : booking?.players || extractPlayersFromDescription(description),
    booking,
    start: new Date(start),
    end: new Date(end),
    allDay,
    isPrivate,
    type,
    raw: event,
  };
}

export async function fetchEvents(timeMin, timeMax) {
  if (CONFIG.appsScriptUrl) {
    return fetchEventsViaAppsScript(timeMin, timeMax);
  }
  if (CONFIG.apiKey) {
    return fetchEventsViaApi(timeMin, timeMax);
  }
  throw new Error('API_KEY_MISSING');
}

async function fetchEventsViaApi(timeMin, timeMax) {
  const params = new URLSearchParams({
    key: CONFIG.apiKey,
    timeMin: timeMin.toISOString(),
    timeMax: timeMax.toISOString(),
    singleEvents: 'true',
    orderBy: 'startTime',
    maxResults: '250',
    timeZone: CONFIG.timezone,
  });

  const url = `${API_BASE}/calendars/${encodeURIComponent(CONFIG.calendarId)}/events?${params}`;
  const res = await fetch(url);

  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(body.error?.message || `HTTP ${res.status}`);
  }

  const data = await res.json();
  return (data.items || []).map(parseEvent);
}

async function fetchEventsViaAppsScript(timeMin, timeMax) {
  const params = new URLSearchParams({
    timeMin: timeMin.toISOString(),
    timeMax: timeMax.toISOString(),
  });

  const url = `${CONFIG.appsScriptUrl}?${params}`;

  try {
    const res = await fetch(url, { redirect: 'follow' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (data.error) throw new Error(data.error);
    return (data.items || []).map(parseEvent);
  } catch {
    // JSONP fallback (Apps Script CORS edge cases)
    return fetchEventsJsonp(timeMin, timeMax);
  }
}

function fetchEventsJsonp(timeMin, timeMax) {
  return new Promise((resolve, reject) => {
    const callback = `ih_cb_${Date.now()}`;
    const params = new URLSearchParams({
      timeMin: timeMin.toISOString(),
      timeMax: timeMax.toISOString(),
      callback,
    });

    const script = document.createElement('script');
    const timer = setTimeout(() => {
      cleanup();
      reject(new Error('Apps Script timeout'));
    }, 15_000);

    function cleanup() {
      clearTimeout(timer);
      delete window[callback];
      script.remove();
    }

    window[callback] = (data) => {
      cleanup();
      if (data.error) reject(new Error(data.error));
      else resolve((data.items || []).map(parseEvent));
    };

    script.src = `${CONFIG.appsScriptUrl}?${params}`;
    script.onerror = () => {
      cleanup();
      reject(new Error('Apps Script request failed'));
    };
    document.head.appendChild(script);
  });
}

export function eventsOverlap(startA, endA, startB, endB) {
  return startA < endB && endA > startB;
}

export function getEventsForSlot(events, slotStart, slotEnd) {
  return events.filter((e) => {
    if (e.allDay) return false;
    return eventsOverlap(e.start, e.end, slotStart, slotEnd);
  });
}

export function eventsFingerprint(eventList) {
  return eventList
    .map((event) => `${event.id}:${event.start.getTime()}:${event.end.getTime()}`)
    .sort()
    .join('|');
}
